package net.dipesh.archFlow.ArchitectHub.enums;


public enum ProjectPermission {

    VIEW_PROJECT,

    VIEW_ARCHITECTURE,
    CREATE_ARCHITECTURE,
    DELETE_ARCHITECTURE,
    UPDATE_ARCHITECTURE,

    VIEW_MEMBER,
    ADD_MEMBER,
    REMOVE_MEMBER,
    UPDATE_MEMBER_ROLE,

    VIEW_MODULE,
    CREATE_MODULE,
    DELETE_MODULE,
    UPDATE_MODULE,

    VIEW_CHANGE_REQUEST,
    CREATE_CHANGE_REQUEST,
    APPROVE_CHANGE_REQUEST,

    VIEW_TECH_STACK,
    CREATE_TECH_STACK,
    DELETE_TECH_STACK,
    UPDATE_TECH_STACK,


    VIEW_MANAGER,
    CREATE_MANAGER,
    DELETE_MANAGER,

    VIEW_AUDIT_LOG,

    UPDATE_PROJECT,

    DELETE_PROJECT


}
